server_name = "localhost"
platform_name = "Android"
device_name = "192.168.240.112:5555"
app_package = "com.zoodfood.express.stage"
app_activity = "com.zoodfood.express.ui.login.LoginActivity"
android_automation = "UIAutomator2"
auto_grant_permissions = "true"
