# login_label = '//[@test()="ورود"]'
phone_number_input = 'com.zoodfood.express.stage:id/lyt_login_txtPhone'
continue_button = 'com.zoodfood.express.stage:id/activity_login_txtAction'
otp_page_label = '//*[@text="رمز یک‌بار مصرف برای شماره ۰۹۱۹۳۶۱۹۴۶۸ ارسال شده است. لطفا آن را در کادر زیر وارد نمایید."]'
otp_input = 'com.zoodfood.express.stage:id/lyt_login_verification_edt'
submit_login_button = 'com.zoodfood.express.stage:id/activity_login_txtAction'
location_button = 'com.android.permissioncontroller:id/permission_allow_foreground_only_button'
click_fake = '//android.widget.FrameLayout[@content-desc="Showing a Map created with Mapbox. Scroll by dragging two fingers. Zoom by pinching two fingers."]/android.view.View'
